version: "3.2"
services:
    client:
        build: ./client
        ports:
            - "3000:3000"
        volumes:
            - ./client:/client
            - ./client/node_modules
        networks:
            - webappnetwork
        depends_on:
            - api
    api:
        build: ./api
        ports:
            - "8081:8081"
        volumes:
            - ./api:/app
            - ./app/node_modules
        depends_on:
            - mongodb
        networks:
            - webappnetwork
    mongodb:
        image: mongo
        restart: always
        hostname: mongodb
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017
        #command: mongod --noauth --smallfiles
        networks:
            - webappnetwork
networks:
    webappnetwork:
        driver: bridge
